site_name: Yatta Documentation
nav:
  - Documentation Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Release Notes: release-notes.md
  - Features:
      - Operators: operators.md
      - Data Types: data-types.md
      - Pattern Matching: pattern-matching.md
      - Module Loader: module-loader.md
      - Polyglot APIs: polyglot.md
  - Standard Library:
      - stdlib/overview.md

theme: readthedocs
